Repository LoginRadius/engineering-portal, pull requests merged in 2020-11, with the labels that each got.

#472 Blog on Github APIs
  content/author.yaml
  content/blog/github-api/GitHub_coverImage.png
  content/blog/github-api/close_issue.png
  content/blog/github-api/comment_on_issue.png
  content/blog/github-api/create_issue.png
  content/blog/github-api/create_repo.png
  content/blog/github-api/followers.png
  content/blog/github-api/index.md
  content/blog/github-api/list_issues.png
  content/blog/github-api/output.png
  content/blog/github-api/user_details.png
  content/blog/github-api/user_follows.png
  content/blog/github-api/user_not_follows.png
Labels: 02-11-2020, In Review, blog-writing, hacktoberfest-accepted

#461 Tweepy blog
  content/blog/beginners-guide-to-tweepy/coverimage.jpg
  content/blog/beginners-guide-to-tweepy/index.md
  content/blog/beginners-guide-to-tweepy/installation.PNG
  content/blog/beginners-guide-to-tweepy/keys.PNG
  content/blog/beginners-guide-to-tweepy/twitterdev.PNG
Labels: 02-11-2020, hacktoberfest-accepted

#396 Walkthrough of AWS Services
  content/blog/a-journey-with-AWS/AWS_API.png
  content/blog/a-journey-with-AWS/AWS_Dynammo.png
  content/blog/a-journey-with-AWS/AWS_EC.png
  content/blog/a-journey-with-AWS/AWS_EC21.png
  content/blog/a-journey-with-AWS/AWS_EC22.png
  content/blog/a-journey-with-AWS/AWS_EC23.png
  content/blog/a-journey-with-AWS/AWS_Lex.png
  content/blog/a-journey-with-AWS/AWS_LexV.png
  content/blog/a-journey-with-AWS/AWS_RDS.png
  content/blog/a-journey-with-AWS/aws.png
  content/blog/a-journey-with-AWS/index.md
Labels: 03-11-2020, In Review, changes requested, hacktoberfest-accepted

#414 bluetooth-controlled-arduino-car-miniature
  content/blog/Bluetooth Controlled Arduino Car Miniature/App Interface.PNG
  content/blog/Bluetooth Controlled Arduino Car Miniature/Arduinocar.PNG
  content/blog/Bluetooth Controlled Arduino Car Miniature/Bluetooth Arduino car Circuit.png
  content/blog/Bluetooth Controlled Arduino Car Miniature/index.md
Labels: 04-11-2020, Ready for Merge, hacktoberfest-accepted

#481 added blog how to test rest api using cucumber
  content/blog/rest-api-cucumber-blog/cucumber_rest_assured.png
  content/blog/rest-api-cucumber-blog/index.md
Labels: 05-11-2020, Ready for Merge, changes requested, cover-image

#509 title: How to send emails through csharp dotnet using smtp
  content/blog/how-to-send-emails-through-csharp-dotnet-using-smtp/coverimage.jpg
  content/blog/how-to-send-emails-through-csharp-dotnet-using-smtp/index.md
Labels: In Review
