Repository LoginRadius/engineering-portal, pull requests merged in 2020-10, with the labels that each got.

#300 Added author info for pull reqeust 262
  content/author.yaml
Labels: Ready to Merge

#262 Graphql Blog - added blog content + assests + author desc
  content/blog/rise-and-rise-of-graphql/graph.png
  content/blog/rise-and-rise-of-graphql/index.md
  content/blog/rise-and-rise-of-graphql/wrapper.png
Labels: Ready to Merge

#296 Updated the minimum cover size to 900px X 600px
  GUIDELINES.md
Labels: In Review

#257 Corrected Typo error
  CONTRIBUTING.md
Labels: Ready to Merge

#310 updated PR checklist and added info about plagiarism in guidelines
  .github/pull_request_template.md
  GUIDELINES.md
Labels: Ready to Merge

#276 Set Focus on input on Click of Search Button
  content/blog/integrating-twitter-social-login/twitter-feat-img.png
  src/components/search.js
Labels: Ready to Merge

#277 Improved the content of golang env blog
  content/blog/environment-variables-in-golang/index.md
Labels: In Review

#275 Replaced a new image of C Sharp logo
  content/blog/exception_handling_in_csharp/CoverImage.jpg
  content/blog/exception_handling_in_csharp/csharplogo.png
  content/blog/exception_handling_in_csharp/index.md
Labels: In Review

#313 updated README to highlight some content
  README.md
Labels: Ready to Merge

#265 fix spelling mistake in hacktoberfest page
  src/pages/hacktoberfest2020.js
  src/templates/hacktoberfest2020.js
Labels: Ready to Merge

#259 Update package.json
  package.json
Labels: Ready to Merge

#292 fix(Image): Replace blog cover image
  content/blog/index-in-mongodb/mongo-db-index1.png
Labels: Ready to Merge

#267 Update README.md
  README.md
Labels: Ready to Merge

#272 Added Proper CoverImage for the Blog - Social Provider TroubleShooting
  content/blog/social-provider-social-sharing-troubleshooting-resources/index.md
  content/blog/social-provider-social-sharing-troubleshooting-resources/social-troubleshoot-150x150.png
  content/blog/social-provider-social-sharing-troubleshooting-resources/social.png
Labels: Ready to Merge

#298 React Lazy Loading blog
  content/blog/lazy-loading-in-react/index.md
  content/blog/lazy-loading-in-react/react.jpg
Labels: 05-10-2020, Ready to Merge, blog-writing

#306 Lets to Let's for grammatical correctness
  content/blog/a-journey-through-react-hooks/index.md
  content/blog/a-webapp-in-deno/index.md
  content/blog/angular-state-management-with-ngxs/index.md
  content/blog/beginners-guide-for-sublime-text/index.md
  content/blog/best-practice-reviewing-qq-app/index.md
  content/blog/build-a-cli-tool-using-deno/index.md
  content/blog/css3-responsive-icons/index.md
  content/blog/how-to-use-maven-dependency-in-eclipse/index.md
  content/blog/implement-facebook-social-login/index.md
  content/blog/integrate-linkedin-social-login-website/index.md
  content/blog/jwt-authentication-with-deno/index.md
  content/blog/mongodb-as-datasource-in-golang/index.md
  content/blog/part-2-creating-a-custom-login-form/index.md
  content/blog/react-state-management/index.md
  content/blog/stream-processing-using-kafka/index.md
  content/blog/use-php-to-generate-filter-portfolio/index.md
  content/blog/what-is-an-api/index.md
  content/blog/wordpress-custom-login-form-part-1/index.md
Labels: In Review

#246 title: blog on GitHub CLI 1.0
  content/author.yaml
  content/blog/COMPLETE GIT (VERSION CONTROL SYSTEM)/Authorize.png
  content/blog/COMPLETE GIT (VERSION CONTROL SYSTEM)/GitHub CLI Tool.png
  content/blog/COMPLETE GIT (VERSION CONTROL SYSTEM)/Installation.gif
  content/blog/COMPLETE GIT (VERSION CONTROL SYSTEM)/angular issue.png
  content/blog/COMPLETE GIT (VERSION CONTROL SYSTEM)/angular pr.png
  content/blog/COMPLETE GIT (VERSION CONTROL SYSTEM)/ghpr.png
  content/blog/COMPLETE GIT (VERSION CONTROL SYSTEM)/index.md
Labels: 05-10-2020, Ready for Merge, blog-writing

#238 feat: add time to read on blog post
  src/components/bio.js
  src/components/card.js
  src/components/pinnedCard.js
  src/components/post.js
  src/templates/author.js
  src/templates/blog-list-template.js
  src/templates/tag.js
  src/utils/timeToRead.js
Labels: In Review

#299 Technical blog related to Handling Data (BigData)#233
  content/blog/handling-cheapest-fuel-data/a.png
  content/blog/handling-cheapest-fuel-data/b.png
  content/blog/handling-cheapest-fuel-data/c.png
  content/blog/handling-cheapest-fuel-data/d.png
  content/blog/handling-cheapest-fuel-data/e.png
  content/blog/handling-cheapest-fuel-data/index.md
Labels: 06-10-2020, Ready for Merge, blog-writing

#337 Breaking down this keyword in javascript
  content/blog/breaking-down-this-keyword-in-javascript/global-context.PNG
  content/blog/breaking-down-this-keyword-in-javascript/index.md
  content/blog/breaking-down-this-keyword-in-javascript/system.PNG
  content/blog/breaking-down-this-keyword-in-javascript/this-image.png
Labels: 06-10-2020, In Review, blog-writing

#328 added about argon2 hashing in the blog post about encryption and hash…
  content/blog/encryption-and-hashing/index.md
Labels: Ready for Merge

#263 ADD Blog on VDN
  content/blog/Learn-About-VDN-for-CyberSecurity/MIM.jpg
  content/blog/Learn-About-VDN-for-CyberSecurity/index.md
Labels: 07-10-2020, Ready for Merge, blog-writing

#365 React Context API blog post
  content/blog/react-contedxt-api/index.md
  content/blog/react-contedxt-api/react.jpg
Labels: 07-10-2020, Ready for Merge

#279 Add blog on Vim
  content/blog/vim-getting-started/BadVim.png
  content/blog/vim-getting-started/Vim.png
  content/blog/vim-getting-started/index.md
  content/blog/vim-getting-started/vscodevim.png
Labels: 08-10-2020, Ready for Merge, blog-writing

#370 BLOCKCHAIN: The new technology of trust
  content/blog/Blockchain-the-new-technology-of -security-trust/CoverPage.jpg
  content/blog/Blockchain-the-new-technology-of -security-trust/block.png
  content/blog/Blockchain-the-new-technology-of -security-trust/index.md
Labels: 08-10-2020, Ready for Merge, blog-writing

#330 Fixed Grammatical errors in "beginners-guide-for-sublime-text" index.md file
  content/blog/beginners-guide-for-sublime-text-3-part-2/index.md
  content/blog/beginners-guide-for-sublime-text/index.md
Labels: Ready for Merge, hacktoberfest-accepted

#301 Added Blog on HTML Email Concept
  content/blog/html-email-concept/email_picture.png
  content/blog/html-email-concept/index.md
Labels: 09-10-2020, In Review, Ready for Merge, blog-writing

#326 Technical blog on implementing full datascience pipeline
  content/blog/Full_data_science_pipeline_implementation/ds.jpg
  content/blog/Full_data_science_pipeline_implementation/index.md
Labels: 09-10-2020, In Review, blog-writing

#377 Added blog on Class activation mapping
  content/blog/class-activation-mapping/Cover.png
  content/blog/class-activation-mapping/index.md
Labels: 10-10-2020, In Review, Ready for Merge, blog-writing

#355 add content upload files using node and multer
  content/blog/upload-files-with-node-and-multer/index.md
  content/blog/upload-files-with-node-and-multer/node-multer-upload.png
Labels: 12-10-2020, In Review, blog-writing

#278 Added new bog: Optimal clusters for KMeans Algorithm
  content/blog/Optimal-Clusters-KMeans/Wcss.png
  content/blog/Optimal-Clusters-KMeans/cover.jpg
  content/blog/Optimal-Clusters-KMeans/index.md
  content/blog/Optimal-Clusters-KMeans/intial.png
Labels: 12-10-2020, In Review, blog-writing

#363 Add blogpost about Containers & Data Structures in C++
  content/blog/cpp-stl-containers/cover.jpg
  content/blog/cpp-stl-containers/index.md
Labels: 13-10-2020, In Review, Ready for Merge, blog-writing

#384 How to implement Secure Enclave in ios app
  content/blog/Secure_Enclave_iOS_app/CoverImage.jpg
  content/blog/Secure_Enclave_iOS_app/image2.jpg
  content/blog/Secure_Enclave_iOS_app/index.md
Labels: 13-10-2020, In Review, Ready for Merge

#338 Technical Blog "Build a Twitter Bot Using NodeJS"
  content/blog/build-a-twitter-bot-using-nodejs/code.png
  content/blog/build-a-twitter-bot-using-nodejs/cover.jpg
  content/blog/build-a-twitter-bot-using-nodejs/index.md
  content/blog/build-a-twitter-bot-using-nodejs/twitter.png
Labels: 14-10-2020, In Review, blog-writing, sample-code

#359 [Blog] Visualizing Data using Leaflet and Netlify
  content/blog/visualizing-data-using-leaflet-and-netlify/deployment.jpg
  content/blog/visualizing-data-using-leaflet-and-netlify/geojson.jpg
  content/blog/visualizing-data-using-leaflet-and-netlify/gitRepo.jpg
  content/blog/visualizing-data-using-leaflet-and-netlify/index.md
  content/blog/visualizing-data-using-leaflet-and-netlify/leaflet.png
  content/blog/visualizing-data-using-leaflet-and-netlify/map.jpg
  content/blog/visualizing-data-using-leaflet-and-netlify/mapIcon.jpg
  content/blog/visualizing-data-using-leaflet-and-netlify/mapInitial.jpg
  content/blog/visualizing-data-using-leaflet-and-netlify/mapPopup.jpg
  content/blog/visualizing-data-using-leaflet-and-netlify/netlify.png
  content/blog/visualizing-data-using-leaflet-and-netlify/netlifySigningUp.jpg
  content/blog/visualizing-data-using-leaflet-and-netlify/repoSelection.jpg
Labels: 14-10-2020, In Review, Ready for Merge, blog-writing

#379 Created Blog speed-up-python-code
  content/blog/speed-up-python-code/index.md
  content/blog/speed-up-python-code/speed-up-python-code-1.jpg
  content/blog/speed-up-python-code/speed-up-python-code.jpg
Labels: 15-10-2020, In Review, Ready for Merge

#364 [Blog] End-to-End Testing with Jest Puppeteer
  content/author.yaml
  content/blog/e2e-testing-with-jest-puppeteer/index.md
  content/blog/e2e-testing-with-jest-puppeteer/jest-puppeteer.png
Labels: 15-10-2020, In Review, blog-writing

#423 Added EOL for the windows OS
  content/blog/eol-end-of-line-or-newline-characters/index.md
Labels: Ready for Merge, hacktoberfest

#389 Add blogpost about Apache Beam
  content/blog/apache-beam-for-dummies/beam_architecture.png
  content/blog/apache-beam-for-dummies/index.md
  content/blog/apache-beam-for-dummies/main.png
  content/blog/apache-beam-for-dummies/pipeline-design.png
  content/blog/apache-beam-for-dummies/timeline-bigdata-frameworks.png
Labels: 16-10-2020, In Review, Ready for Merge, blog-writing

#381 Blog-Using virtual environment in Python
  content/blog/python-virtual-environments/activate.png
  content/blog/python-virtual-environments/activated.png
  content/blog/python-virtual-environments/check.png
  content/blog/python-virtual-environments/deactivate.png
  content/blog/python-virtual-environments/index.md
  content/blog/python-virtual-environments/install.png
  content/blog/python-virtual-environments/name.png
  content/blog/python-virtual-environments/pip.png
  content/blog/python-virtual-environments/python.jpg
  content/blog/python-virtual-environments/version.png
  content/blog/python-virtual-environments/windows.png
Labels: 16-10-2020, In Review, blog-writing

#382 Blog: Start with iOS App Development
  content/blog/Getting_Started_with_ios_app_development/CoverImage.jpg
  content/blog/Getting_Started_with_ios_app_development/Imag1.jpg
  content/blog/Getting_Started_with_ios_app_development/Image2.jpg
  content/blog/Getting_Started_with_ios_app_development/Image3.jpg
  content/blog/Getting_Started_with_ios_app_development/Image4.jpg
  content/blog/Getting_Started_with_ios_app_development/Image5.jpg
  content/blog/Getting_Started_with_ios_app_development/Image6.jpg
  content/blog/Getting_Started_with_ios_app_development/index.md
  content/blog/Secure_Enclave_iOS_app/CoverImage.jpg
  content/blog/Secure_Enclave_iOS_app/image2.jpg
Labels: 19-10-2020, In Review, blog-writing

#437 Blog Typos
  content/blog/3-simple-ways-to-secure-your-websites-applications/index.md
  content/blog/a-journey-from-node-to-golang/index.md
  content/blog/adding-multi-threading-to-javascript-using-web-workers/index.md
Labels: In Review

#346 Blog on how to make a telegram bot
  content/blog/how-to-make-telegram-bot/bot.png
  content/blog/how-to-make-telegram-bot/index.md
Labels: 20-10-2020, In Review, blog-writing

#416 title: three ways to do crud operations on redis
  content/blog/three-ways-to-do-crud-operations-on-redis/browser.png
  content/blog/three-ways-to-do-crud-operations-on-redis/connect.png
  content/blog/three-ways-to-do-crud-operations-on-redis/filter.png
  content/blog/three-ways-to-do-crud-operations-on-redis/index.md
  content/blog/three-ways-to-do-crud-operations-on-redis/index.png
Labels: 21-10-2020, In Review, blog-writing

#344 Blog for Hacktoberfest : Traversing the realms of Quantum Network
  content/blog/Traversing the realms of Quantum Network/Phio-Network-by-Quantum-Xchange-1.jpg
  content/blog/Traversing the realms of Quantum Network/index.md
  content/blog/Traversing the realms of Quantum Network/quantum_comp_FB.png
Labels: 21-10-2020, In Review

#383 Blogpost on Best Hacking Tools
  content/blog/Best-hacking-tools/John-The-Ripper.png
  content/blog/Best-hacking-tools/NIKTO-Scanner.png
  content/blog/Best-hacking-tools/Wireshark_Logo.png
  content/blog/Best-hacking-tools/angryipscanner.jpg
  content/blog/Best-hacking-tools/burpsuite.png
  content/blog/Best-hacking-tools/cover1.jpg
  content/blog/Best-hacking-tools/index.md
  content/blog/Best-hacking-tools/metasploit_logo.png
  content/blog/Best-hacking-tools/nmap.jpg
Labels: 22-10-2020, In Review, Ready for Merge, blog-writing

#434 RPA Blog
  content/blog/importance-of-rpa/RPA.jpg
  content/blog/importance-of-rpa/index.md
Labels: 23-10-2020, In Review, Ready for Merge, blog-writing

#401 Blog post on creating a new blog with jekyll & github pages
  content/blog/setup-blog-in-minutes-with-jekyll/enable-github-pages.png
  content/blog/setup-blog-in-minutes-with-jekyll/github-pages-action.png
  content/blog/setup-blog-in-minutes-with-jekyll/index.md
  content/blog/setup-blog-in-minutes-with-jekyll/jekyll-github-pages.png
  content/blog/setup-blog-in-minutes-with-jekyll/new-blog.png
Labels: 26-10-2020, In Review, blog-writing

#366 HacktoberFest: Blog about Eternal Blue
  .gitignore
  content/blog/eternal-blue-retrospective/etbluecover.png
  content/blog/eternal-blue-retrospective/index.md
Labels: 27-10-2020, In Review, Ready for Merge, blog-writing

#443 Add blog on how to create an accordion with HTML and CSS only
  content/blog/css3-accordion/css3-accordion.png
  content/blog/css3-accordion/index.md
  content/blog/css3-accordion/plain-html.png
Labels: 27-10-2020, Ready for Merge, hacktoberfest-accepted

#466 Added info for JWT token
  content/blog/everything-you-want-to-know-about-authorization-headers/index.md
Labels: Ready for Merge, hacktoberfest-accepted

#453 Added jamstack blog
  content/blog/jamstack-introduction/image1.png
  content/blog/jamstack-introduction/index.md
  content/blog/jamstack-introduction/title-image.jpg
Labels: 29-10-2020, In Review, blog-writing

#464 React Speech Recognition- Quick look
  content/author.yaml
  content/blog/quick-look-at-react-speech-recognition/index.md
  content/blog/quick-look-at-react-speech-recognition/mic.png
  content/blog/quick-look-at-react-speech-recognition/styledExample.png
Labels: 29-10-2020, In Review, blog-writing

#459 Introduction To Android Studio Blog
  content/blog/introduction-to-android-studio/configure.png
  content/blog/introduction-to-android-studio/cover.png
  content/blog/introduction-to-android-studio/empty.png
  content/blog/introduction-to-android-studio/gradle.png
  content/blog/introduction-to-android-studio/index.md
  content/blog/introduction-to-android-studio/welcomepage.png
  content/blog/introduction-to-android-studio/xml.png
Labels: 30-10-2020

#468 Adding Blog for Login Screen Testing Tips
  content/blog/loginscreen_testing_tips/CoverImage.png
  content/blog/loginscreen_testing_tips/Login-Page.png
  content/blog/loginscreen_testing_tips/index.md
Labels: 30-10-2020, In Review, Ready for Merge, hacktoberfest-accepted
