Repository LoginRadius/engineering-portal, pull requests merged in 2021-12, with the labels that each got.

#826 Blog Post: Authenticate Flask API Using JWT
  content/author.yaml
  content/guest-post/securing-flask-api-with-jwt/coverImage.png
  content/guest-post/securing-flask-api-with-jwt/index.md
Labels: In Review

#724 Added new blog of php api using jwt
  content/author.yaml
  content/guest-post/securing-php-api-with-jwt/index.md
  content/guest-post/securing-php-api-with-jwt/jwt.png
Labels: In Review

#931 Update Settings “authors”
  content/authors.yml
Labels: netlify-cms/pending_publish

#933 Update Settings “authors”
  content/authors.yaml
Labels: netlify-cms/pending_publish

#934 Create LoginRadius Blog “2021-12-23-new-blog”
  assets/uploads/announcing-new-look-of-loginradius-v01.02_cover.png
  content/2021-12-23-new-blog.md
Labels: netlify-cms/pending_publish

#927 Updated all the suggestions & the image also
  content/author.yaml
  content/integrate-linkedin-social-login-website/index.md
  content/react-security-vulnerabilities/index.md
  content/react-security-vulnerabilities/react-security.png
Labels: changes requested

#936 Create LoginRadius Blog “new-blog/index.md”
  content/new-blog/announcing-new-look-of-loginradius-v01.02_cover.png
  content/new-blog/index.md.md
Labels: netlify-cms/pending_publish

#937 Create LoginRadius Blog “netlify-cms/index.md”
  content/netlify-cms/announcing-new-look-of-loginradius-v01.02_cover.png
  content/netlify-cms/index.md.md
Labels: netlify-cms/pending_publish
