Repository LoginRadius/engineering-portal, pull requests merged in 2022-01, with the labels that each got.

#942 Blog Local Storage vs Session Storage vs Cookies added
  content/author.yaml
  content/guest-post/local-storage-vs-session-storage-vs-cookies/application-tab-screenshot.PNG
  content/guest-post/local-storage-vs-session-storage-vs-cookies/blog-banner.png
  content/guest-post/local-storage-vs-session-storage-vs-cookies/comparison-table.png
  content/guest-post/local-storage-vs-session-storage-vs-cookies/index.md
  content/guest-post/local-storage-vs-session-storage-vs-cookies/local-storage-tab-screenshot.PNG
  content/guest-post/local-storage-vs-session-storage-vs-cookies/session-storage-example-1.PNG
  content/guest-post/local-storage-vs-session-storage-vs-cookies/session-storage-example-2.PNG
  content/guest-post/local-storage-vs-session-storage-vs-cookies/session-storage-tab-screenshot.PNG
Labels: changes requested

#928 Blog - Next.js Authentication
  content/author.yaml
  content/guest-post/nextjs-authentication-guide/index.md
  content/guest-post/nextjs-authentication-guide/next-authentication.png
  content/guest-post/nextjs-authentication-guide/profile-page.png
Labels: Ready for Merge

#950 Node Auth guide
  content/guest-post/nodejs-authentication-guide/Hashedregisterroute.jpeg
  content/guest-post/nodejs-authentication-guide/coverimage.jpeg
  content/guest-post/nodejs-authentication-guide/crypto.jpeg
  content/guest-post/nodejs-authentication-guide/deleteroute.jpeg
  content/guest-post/nodejs-authentication-guide/hashedloginroute.jpeg
  content/guest-post/nodejs-authentication-guide/index.md
  content/guest-post/nodejs-authentication-guide/loginradius.png
  content/guest-post/nodejs-authentication-guide/loginradius1.png
  content/guest-post/nodejs-authentication-guide/loginroute.jpeg
  content/guest-post/nodejs-authentication-guide/nodebycrypt.jpeg
  content/guest-post/nodejs-authentication-guide/registerRoute.jpeg
  content/guest-post/nodejs-authentication-guide/updateroute.jpeg
Labels: In Review
